# Generated by Django 5.0.6 on 2024-06-02 09:59

import Server.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50)),
                ('file_size', models.CharField(max_length=50)),
                ('file_type', models.CharField(max_length=50)),
                ('file_dir', models.CharField(max_length=50)),
                ('file_suffix', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='user_upload_file/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserFileInfo',
            fields=[
                ('file_id', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False, verbose_name='文件ID')),
                ('file_org_name', models.CharField(max_length=255)),
                ('file_server_name', models.CharField(max_length=255)),
                ('file_size', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=255)),
                ('file_md5', models.CharField(max_length=50)),
                ('file_finish_time', models.DateTimeField(null=True)),
                ('has_qr_code', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='账号ID')),
                ('user_account', models.CharField(default=Server.models.generate_account_number, help_text='系统自动生成的16位数字账号', max_length=16, verbose_name='账号')),
                ('user_password', models.CharField(max_length=16)),
                ('phone_number', models.CharField(max_length=50)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
