# Generated by Django 5.0.6 on 2024-05-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50)),
                ('file_size', models.CharField(max_length=50)),
                ('file_type', models.CharField(max_length=50)),
                ('file_dir', models.CharField(max_length=50)),
                ('file_suffix', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '文件信息',
                'verbose_name_plural': '文件信息',
                'db_table': 't_file_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='user_upload_file/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
